# apiVersion: v1
# kind: Pod
# metadata:
#   name: testfrontend
# spec:
#   containers:
#   - name: testfrontend
#     image: sameerbhat/backend-app

apiVersion: apps/v1
kind: Deployment
metadata:
  name: testbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testbackend
  template:
    metadata:
      labels:
        app: testbackend
    spec:
      containers:
      - name: testbackend
        image: sameerbhat/testbackend:latest

--- 
apiVersion: v1
kind: Service
metadata:
  name: testbackend
spec:
  selector:
    app: testbackend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP