pipeline {
    agent any
    environment {
        DOCKER_IMAGE = 'sameerbhat/testbackend:latest'
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/SameerBhat/ci-cd-example.git'
            }
        }
        stage('Build Backend') {
            steps {
                script {
                    sh 'cd backend'
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }
        stage('Docker Build and Push') {
            steps {
                script {
                    docker.build(env.DOCKER_IMAGE).push()
                }
            }
        }
        stage('Cleanup') {
            steps {
                sh "docker rmi $DOCKER_IMAGE"
            }
        }
    }
}
