pipeline {
    agent any
    tools { nodejs "node22" }
    environment {
        PATH = "$PATH:$WORKSPACE/node_modules/.bin"
        DOCKER_IMAGE = 'sameerbhat/testbackend:latest'
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/SameerBhat/ci-cd-example.git'
            }
        }
        stage('Build Backend') {
            steps {
                 script {
                                   sh '''
                                       cd frontend
                                       npm install
                                       npm run build
                                   '''
                               }
            }
        }
        stage('Docker Build and Push') {
            steps {
                script {
                     dir('frontend') {
                                           docker.build(env.DOCKER_IMAGE).push()
                                       }
                }
            }
        }
        stage('Cleanup') {
            steps {
                sh "docker rmi $DOCKER_IMAGE"
            }
        }
    }
}
